//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef _MyPrimaryGeneratorGPS_H_
#define _MyPrimaryGeneratorGPS_H_

#include "G4VUserPrimaryGeneratorAction.hh"
#include "CosmicRay.hh"
#include "CosmicRayList.hh"
#include "globals.hh"

class G4GeneralParticleSource;
class G4Event;

class MyPrimaryGeneratorGPS : public G4VUserPrimaryGeneratorAction
{
public:
    MyPrimaryGeneratorGPS();
    //MyPrimaryGeneratorGPS(PGPSConfig);
    ~MyPrimaryGeneratorGPS();

    virtual void GeneratePrimaries(G4Event *anEvent);

private:
    G4GeneralParticleSource *fParticleGun;
    CosmicRay* fCosmicRay;
    CosmicRayList* fCosmicRayList;
};

#endif
